name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: flask-cicd-demo
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint
        run: flake8 app tests

      - name: Test
        run: pytest

  build-and-push:
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ env.DOCKERHUB_TOKEN }}" | docker login -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ github.sha }}
          docker tag $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ github.sha }} $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted  # Replace with proper runner label
    steps:
      - uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Set image tag in Helm values
        run: |
          helm upgrade --install flask-app ./helm/flask-app \
            --set image.repository=$DOCKERHUB_USERNAME/$IMAGE_NAME \
            --set image.tag=latest

  # jobs:
  # deploy:
  #   runs-on: self-hosted  # Your runner on k3s node
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Setup kubectl
  #       uses: azure/setup-kubectl@v3
  #       with:
  #         version: 'latest'

  #     - name: Setup KUBECONFIG
  #       run: echo "$KUBECONFIG_CONTENT" > $HOME/.kube/config
  #       env:
  #         KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG }}

  #     - name: Install NGINX Ingress Controller
  #       run: |
  #         kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0/deploy/static/provider/k3s/deploy.yaml

  #     - name: Wait for ingress controller pods to be ready
  #       run: |
  #         kubectl rollout status deployment/ingress-nginx-controller -n ingress-nginx --timeout=120s

  #     - name: Deploy Flask app via Helm
  #       run: |
  #         helm upgrade --install flask-app ./helm/flask-app \
  #           --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/flask-cicd-demo \
  #           --set image.tag=latest
  #       env:
  #         KUBECONFIG: $HOME/.kube/config

