name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: flask-cicd-demo
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint
        run: flake8 app tests

      - name: Test
        run: pytest

  build-and-push:
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ env.DOCKERHUB_TOKEN }}" | docker login -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ github.sha }}
          docker tag $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ github.sha }} $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted  # Replace with proper runner label
    steps:
      - uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Set image tag in Helm values
        run: |
          helm upgrade --install flask-app ./helm/flask-app \
            --set image.repository=$DOCKERHUB_USERNAME/$IMAGE_NAME \
            --set image.tag=latest
